import { selectMenu } from './select-menu.mjs';
import { chromium } from 'playwright';
import { preview } from 'vite';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { createHash } from 'node:crypto';
import assert from 'node:assert/strict';
import { taggedWav } from './library-fixtures.mjs';
import { dropLyricFile } from './drop-lyric-file.mjs';

const development = process.argv.includes('--dev');
const origin = development ? 'http://127.0.0.1:3000' : 'http://127.0.0.1:4178';
const server = development ? null : await preview({ preview: { host: '127.0.0.1', port: 4178, strictPort: true } });
const root = resolve('test-results/studio'), profile = resolve(`test-results/studio-profile-${Date.now()}`);
await mkdir(root, { recursive: true });
const audioName = 'Composer - 繁體 & Light.wav';
const audioPath = resolve(root, audioName), audioBytes = taggedWav({ TIT2: 'Workshop song' }, [], undefined, 12);
await writeFile(audioPath, audioBytes);
await writeFile(resolve(root, 'next.wav'), taggedWav({ TIT2: 'Next song' }, [], undefined, 12));
await writeFile(resolve(root, 'invalid.ttml'), '<tt><body><p>Broken');
await writeFile(resolve(root, 'words.ttml'), '<tt xmlns="http://www.w3.org/ns/ttml" xmlns:ttm="http://www.w3.org/ns/ttml#metadata"><body><div><p begin="1s" end="3s"><span begin="0s" end="1s">One </span><span begin="1s" end="2s">word</span><span ttm:role="x-translation">译文</span></p></div></body></tt>');
const lyrics = 'A & <light> "now"\n繁體中文與星光 🌓\nThe last line';
const errors = [], external = [], violations = [], checks = [];
let context, page, phase = 'startup';
const launch = async () => {
  const context = await chromium.launchPersistentContext(profile, { headless: true, channel: process.env.BROWSER_CHANNEL || 'msedge', viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
  await context.route('**/*', route => {
    if (new URL(route.request().url()).origin !== origin) { external.push(route.request().url()); return route.abort(); }
    return route.continue();
  });
  await context.exposeBinding('recordStudioViolation', (_, value) => violations.push(value));
  await context.addInitScript(() => {
    window.__audioCount = 0; const Audio = window.Audio;
    window.Audio = class extends Audio { constructor(...args) { super(...args); window.__audioCount++; } };
    document.addEventListener('securitypolicyviolation', event => window.recordStudioViolation(event.violatedDirective + ': ' + event.blockedURI));
  });
  for (const page of context.pages()) { page.on('pageerror', error => errors.push(phase + ': ' + error.message)); page.on('dialog', dialog => dialog.accept()); }
  return context;
};
const studioBar = () => page.getByRole('contentinfo', { name: 'Studio player', exact: true });
const playerBar = () => page.getByRole('contentinfo', { name: 'Player', exact: true });
const saved = () => page.locator('.studio-save-status').filter({ hasText: 'Draft saved' }).waitFor();
const enterStudio = async () => { await page.getByRole('button', { name: 'Open app menu', exact: true }).click(); await page.getByRole('menuitem', { name: 'Lyric Studio', exact: true }).click(); await page.getByLabel('Lyrics line 1', { exact: true }).waitFor(); };
const seek = async value => {
  await page.getByRole('slider', { name: 'Playback progress', exact: true }).evaluate((input, value) => {
    Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(input, String(value));
    input.dispatchEvent(new Event('input', { bubbles: true })); input.dispatchEvent(new Event('change', { bubbles: true }));
  }, value);
  await page.waitForFunction(value => Math.abs(document.querySelector('audio').currentTime - value) < .2, value);
};
const chooseExport = async type => { await page.getByRole('button', { name: 'Export ▾', exact: true }).click(); const item = page.getByRole('menuitem', { name: `Export ${type}`, exact: true }); await item.click(); await item.waitFor({ state: 'hidden' }); };
const drafts = () => page.evaluate(() => new Promise((resolve, reject) => {
  const open = indexedDB.open('local-music-library'); open.onerror = () => reject(open.error);
  open.onsuccess = () => { const db = open.result, tx = db.transaction('settings'), get = tx.objectStore('settings').getAll(); get.onsuccess = () => resolve(get.result.filter(value => value?.lines)); tx.oncomplete = () => db.close(); };
}));
try {
  context = await launch(); page = context.pages()[0];
  await page.goto(origin); await enterStudio();
  assert.equal(await page.locator('.offline-library, .offline-playing-bar').count(), 0);
  await page.getByRole('button', { name: 'Paste lyrics', exact: true }).click();
  const pasteDialog = page.getByRole('dialog', { name: 'Paste lyrics', exact: true });
  await pasteDialog.getByLabel('Paste whole lyrics', { exact: true }).fill(lyrics);
  await pasteDialog.getByRole('button', { name: 'Use lyrics', exact: true }).click(); await pasteDialog.waitFor({ state: 'hidden' });
  assert.equal(await page.locator('.studio-row').count(), 3);
  phase = 'plain editing and structural operations';
  await page.getByLabel('Lyrics line 1', { exact: true }).evaluate(element => { element.focus(); element.setSelectionRange(2, 2); });
  await page.getByLabel('Lyrics line 1', { exact: true }).press('Enter');
  assert.equal(await page.locator('.studio-row').count(), 4);
  await page.getByRole('button', { name: 'Actions for line 1', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Merge with next', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Merge with next', exact: true }).waitFor({ state: 'hidden' });
  assert.equal(await page.locator('.studio-row').count(), 3);
  await page.getByRole('button', { name: 'Undo', exact: true }).click(); await page.getByRole('button', { name: 'Undo', exact: true }).click();
  assert.equal(await page.getByLabel('Lyrics line 1', { exact: true }).inputValue(), lyrics.split('\n')[0]);
  await page.getByRole('button', { name: '＋ Add line', exact: true }).click();
  await page.getByRole('button', { name: 'Actions for line 4', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Remove line', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Remove line', exact: true }).waitFor({ state: 'hidden' });
  assert.equal(await page.locator('.studio-row').count(), 3);
  await saved();
  await page.getByLabel('Choose studio audio', { exact: true }).setInputFiles(audioPath);
  await page.waitForFunction(() => document.querySelector('audio')?.duration === 12);
  await page.getByRole('heading', { name: 'Lyric Studio', exact: true }).waitFor(); await saved();
  assert.equal(await page.getByLabel('Lyrics line 2', { exact: true }).inputValue(), '繁體中文與星光 🌓');
  assert.equal(await page.locator('.studio-song strong').textContent(), 'Workshop song');
  checks.push('the top-left app menu opens a separate studio without a library sidebar; plain-text paste, split, merge, add, remove and undo work; choosing audio retains an untitled draft');
  phase = 'validation and marking actual time';
  await chooseExport('TTML');
  await page.getByRole('alert').filter({ hasText: 'Export needs attention' }).waitFor();
  assert.equal(await page.getByLabel('Start time line 1', { exact: true }).getAttribute('aria-invalid'), 'true');
  await seek(1); await page.getByRole('button', { name: 'Select line 1', exact: true }).click();
  await page.getByRole('button', { name: 'Mark current line ↓', exact: true }).click();
  assert.equal(await page.getByLabel('Start time line 1', { exact: true }).inputValue(), '00:01.000');
  assert.equal(await page.getByRole('button', { name: 'Select line 2', exact: true }).getAttribute('aria-pressed'), 'true');
  await seek(4); await studioBar().getByRole('button', { name: 'Play', exact: true }).click();
  const beforeMark = await page.evaluate(() => document.querySelector('audio').currentTime);
  await page.keyboard.press('ArrowDown');
  const afterMark = await page.evaluate(() => document.querySelector('audio').currentTime);
  await studioBar().getByRole('button', { name: 'Pause', exact: true }).click();
  const second = await page.getByLabel('Start time line 2', { exact: true }).inputValue();
  const secondSeconds = Number(second.split(':')[1]);
  assert.ok(secondSeconds >= beforeMark - .01 && secondSeconds <= afterMark + .01);
  await seek(8); await page.getByRole('button', { name: 'Select line 3', exact: true }).focus(); await page.keyboard.press('ArrowDown');
  assert.equal(await page.getByLabel('Start time line 3', { exact: true }).inputValue(), '00:08.000');
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  assert.equal(await page.getByLabel('Start time line 3', { exact: true }).inputValue(), '');
  await page.keyboard.press('ArrowDown');
  await page.getByLabel('End time line 1', { exact: true }).fill('00:02.500');
  await page.getByRole('button', { name: 'Shift timing', exact: true }).click();
  await page.getByLabel('Shift all times in seconds', { exact: true }).fill('0.5');
  await page.getByRole('button', { name: 'Apply shift', exact: true }).click();
  assert.equal(await page.getByLabel('Start time line 1', { exact: true }).inputValue(), '00:01.500');
  assert.equal(await page.getByLabel('End time line 1', { exact: true }).inputValue(), '00:03.000');
  assert.equal(await page.getByLabel('End time line 3', { exact: true }).getAttribute('placeholder'), '00:12.000');
  await page.getByLabel('End time line 1', { exact: true }).fill('0'); await chooseExport('TTML');
  await page.locator('.studio-row-error').filter({ hasText: 'end must be later than start' }).waitFor();
  await page.getByLabel('End time line 1', { exact: true }).fill('00:03.000');
  await page.getByRole('button', { name: 'Listen to line 1', exact: true }).click();
  await page.waitForFunction(() => !document.querySelector('audio').paused && document.querySelector('audio').currentTime >= 1.5 && document.querySelector('audio').currentTime < 2.5);
  await studioBar().getByRole('button', { name: 'Pause', exact: true }).click();
  await selectMenu(page, 'Playback speed', '0.5');
  assert.equal(await page.evaluate(() => document.querySelector('audio').playbackRate), .5);
  await saved();
  checks.push('button and ArrowDown marks record actual audio time and advance selection; undo restores a mark, per-line ends and global shift work, invalid exports focus the row, and listen/rate controls use the existing audio');
  phase = 'responsive studio';
  await page.screenshot({ path: resolve(root, 'studio-desktop.png') });
  for (const width of [850, 390, 320]) {
    await page.setViewportSize({ width, height: 900 });
    await page.waitForTimeout(100);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), true, `No page overflow at ${width}`);
    assert.equal(await studioBar().getByRole('slider', { name: 'Playback progress', exact: true }).isVisible(), true);
  }
  await page.screenshot({ path: resolve(root, 'studio-mobile.png') });
  await page.setViewportSize({ width: 1440, height: 1000 });
  phase = 'dual downloads';
  const ttmlDownload = page.waitForEvent('download', download => download.suggestedFilename().endsWith('.ttml'));
  const lrcDownload = page.waitForEvent('download', download => download.suggestedFilename().endsWith('.lrc'));
  await chooseExport('both');
  const ttmlFile = await ttmlDownload, lrcFile = await lrcDownload;
  assert.equal(ttmlFile.suggestedFilename(), 'Composer - 繁體 & Light.ttml'); assert.equal(lrcFile.suggestedFilename(), 'Composer - 繁體 & Light.lrc');
  const ttmlPath = resolve(root, 'exported.ttml'), lrcPath = resolve(root, 'exported.lrc');
  await ttmlFile.saveAs(ttmlPath); await lrcFile.saveAs(lrcPath);
  const ttml = await readFile(ttmlPath, 'utf8'), lrc = await readFile(lrcPath, 'utf8');
  assert.match(ttml, /&lt;light&gt;/); assert.match(ttml, /繁體中文與星光 🌓/); assert.match(ttml, /end="12.000s"/); assert.match(lrc, /\[00:03.000\]\n/);
  const readyDialog = page.getByRole('dialog', { name: 'Lyrics ready', exact: true });
  await readyDialog.getByRole('button', { name: 'Close', exact: true }).click(); await readyDialog.waitFor({ state: 'hidden' });
  checks.push('both UTF-8 downloads use the original audio basename, preserve Chinese and XML special characters, and retain explicit gaps and the real final audio end');
  phase = 'import and explicit flattening';
  await page.getByLabel('Choose studio lyrics', { exact: true }).setInputFiles(lrcPath);
  const importPreview = page.getByRole('dialog', { name: 'Import into Lyric Studio', exact: true });
  await importPreview.getByRole('button', { name: 'Use line timings', exact: true }).click(); await importPreview.waitFor({ state: 'hidden' });
  assert.equal(await page.getByLabel('Start time line 1', { exact: true }).inputValue(), '00:01.500');
  await page.getByLabel('Choose studio lyrics', { exact: true }).setInputFiles(resolve(root, 'words.ttml'));
  await importPreview.getByText(/Word timings will become line timings/).waitFor(); await importPreview.getByText(/Translations and romanization/).waitFor();
  await importPreview.getByRole('button', { name: 'Use line timings', exact: true }).click(); await importPreview.waitFor({ state: 'hidden' });
  assert.equal(await page.getByLabel('Lyrics line 1', { exact: true }).inputValue(), 'One word');
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await page.getByLabel('Choose studio lyrics', { exact: true }).setInputFiles(resolve(root, 'invalid.ttml'));
  await page.locator('.studio-message').filter({ hasText: 'not valid XML' }).waitFor();
  assert.equal(await page.locator('.studio-row').count(), 3);
  checks.push('existing LRC and TTML import into editable lines; word/annotation conversion is disclosed before replacing, undo recovers the old draft, and malformed files do not replace it');
  phase = 'failed draft persistence and recovery';
  await saved();
  const previousDraft = (await drafts()).find(draft => draft.audioName === audioName);
  await page.evaluate(() => {
    window.__put = IDBObjectStore.prototype.put;
    IDBObjectStore.prototype.put = function(...args) { if (this.name === 'settings' && String(args[1]).startsWith('lyric-studio:')) throw new DOMException('Test quota', 'QuotaExceededError'); return window.__put.apply(this, args); };
  });
  await page.getByLabel('Lyrics line 3', { exact: true }).fill('The last line — recovered');
  await page.locator('.studio-warning').filter({ hasText: 'Draft could not be saved' }).waitFor();
  assert.equal((await drafts()).find(draft => draft.audioName === audioName).lines[2].text, previousDraft.lines[2].text);
  await page.reload(); await page.getByLabel('Lyrics line 3', { exact: true }).waitFor(); await saved();
  assert.equal(await page.getByLabel('Lyrics line 3', { exact: true }).inputValue(), 'The last line — recovered');
  await page.getByLabel('Lyrics line 3', { exact: true }).fill('The last line'); await saved();
  checks.push('draft save failure is visible and does not overwrite the committed draft; the small text recovery journal restores the latest edit after reload');
  phase = 'same audio across entry and end policy';
  await page.getByRole('link', { name: 'Back to player', exact: true }).click();
  assert.equal(await page.evaluate(() => document.querySelector('audio').playbackRate), 1);
  await page.getByRole('button', { name: 'Import music', exact: true }).first().click();
  const audioDialog = page.getByRole('dialog', { name: 'Import local music', exact: true });
  await audioDialog.getByLabel('Choose audio files', { exact: true }).setInputFiles(resolve(root, 'next.wav'));
  await audioDialog.getByRole('status').filter({ hasText: 'Added 1 files' }).waitFor();
  await audioDialog.getByRole('button', { name: 'Close', exact: true }).click(); await audioDialog.waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: 'Workshop song Local file', exact: true }).click();
  await page.evaluate(() => window.__firstAudio = document.querySelector('audio'));
  const priorTime = await page.evaluate(() => document.querySelector('audio').currentTime);
  await enterStudio();
  assert.equal(await page.evaluate(() => document.querySelector('audio') === window.__firstAudio), true);
  assert.ok(await page.evaluate(() => document.querySelector('audio').currentTime) >= priorTime);
  const src = await page.evaluate(() => document.querySelector('audio').src);
  await seek(11.8);
  await page.waitForFunction(() => document.querySelector('audio').ended && document.querySelector('audio').paused);
  assert.equal(await page.evaluate(() => document.querySelector('audio').src), src);
  assert.equal(await page.evaluate(() => window.__audioCount), 1);
  checks.push('entering from the player retains the playing song, time and audio instance; at the end Studio stays on that song despite queued songs; leaving restores normal playback speed');
  phase = 'exported files reimport into the player';
  await page.getByRole('link', { name: 'Back to player', exact: true }).click();
  await playerBar().getByRole('button', { name: 'Lyrics', exact: true }).click();
  for (const [index, path] of [ttmlPath, lrcPath].entries()) {
    if (index) await dropLyricFile(page, path);
    else await page.getByRole('button', { name: 'Import lyrics', exact: true }).click();
    const dialog = page.getByRole('dialog', { name: 'Import local lyrics', exact: true });
    await dialog.getByLabel('Choose lyric file', { exact: true }).setInputFiles(path);
    await dialog.getByRole('button', { name: 'Save lyrics', exact: true }).click(); await dialog.waitFor({ state: 'hidden' });
    await seek(2);
    await page.waitForFunction(() => document.querySelector('.lyric-row[data-active]')?.textContent.includes('A & <light> "now"'));
    await seek(3.5); assert.equal(await page.locator('.lyric-row[data-active]').count(), 0);
    await seek(9);
    await page.waitForFunction(() => document.querySelector('.lyric-row[data-active]')?.textContent.includes('The last line'));
  }
  checks.push('downloaded TTML and LRC both reimport through the real player dialog and highlight the right text at real audio positions, including an instrumental gap');
  phase = 'full process restart';
  await context.close(); context = await launch(); page = context.pages()[0];
  await page.goto(origin + '/studio'); await page.getByLabel('Lyrics line 3', { exact: true }).waitFor(); await saved();
  assert.equal(await page.getByLabel('Lyrics line 3', { exact: true }).inputValue(), 'The last line');
  assert.equal(await page.getByLabel('Start time line 1', { exact: true }).inputValue(), '00:01.500');
  await page.waitForFunction(() => document.querySelector('audio').duration === 12);
  assert.equal(await page.evaluate(() => document.querySelector('audio').paused), true);
  assert.equal(createHash('sha256').update(await readFile(audioPath)).digest('hex'), createHash('sha256').update(audioBytes).digest('hex'));
  checks.push('a full browser process restart restores the last song, draft text and times without autoplay; the original audio checksum is unchanged');
  assert.deepEqual(errors, []); assert.deepEqual(external, []); assert.deepEqual(violations, []);
  const report = { result: 'passed', mode: development ? 'development' : 'production', checks, errors, external, violations };
  await writeFile(resolve(root, `studio-${report.mode}.json`), JSON.stringify(report, null, 2)); console.log(JSON.stringify(report, null, 2));
} catch (error) { console.error(JSON.stringify({ phase, errors, external, violations })); await page?.screenshot({ path: resolve(root, 'studio-failure.png') }).catch(() => {}); throw error; }
finally { await context?.close(); if (server) await new Promise(resolve => server.httpServer.close(resolve)); }

